### ISSUE TITLE
Cannot add PPA: 'ppa:ondrej/php'. Please check that the PPA name or format is correct

### ISSUE THREAD

**Issue by achrafbsecure** [whatwedo/docker-base-images#20]
I 'm using ubuntu 12.04  and i want to upgrade my php version from 5.4 to 5.6
`Cannot add PPA: 'ppa:ondrej/php'.
Please check that the PPA name or format is correct`
 i install   `sudo apt-get install --reinstall ca-certificates` . but i still have the sae issue . could someone help me please??

**Comment by n3r0-ch** [comment]
Please use the new `v2.0` image
