### ISSUE TITLE
v2.0 released today 🎉

### ISSUE THREAD

**Issue by n3r0-ch** [whatwedo/docker-base-images#28]
Today, we released the `v2.0` version of our Docker images. It have been a long journey since version `v1.0`. Due to the end of life of many of software used in the `v1.x`, we decided to do a complete rewrite.

Below, you will find the most important changes:

* Common
    * All images run with Alpine 3.9 instead of Ubuntu 14.04.
    * There will be no `latest` tag available in future. Using a `latest` tag can cause a lot of troubles, especially if you are using Docker in production. Currently there is a latest tag available due to compatibility issues, but it will be removed in summer 2019. Please use the current stable tag (`v2.0`) instead or for the old images `v1.7`.
    * All `v2.0` images are a lot smaller than the old `v1.x` images. e. g. `bash` oder `make` aren't part of the images anymore. They are tools which often aren't needed on production.
* Init system
    * The script `/bin/firstboot` and `/bin/everyboot` do not exist anymore. Instead your are able to place one or multiple scripts in the `/etc/upstart` directory. These scripts are going to be automatically executed in alphabetical order at the container startup. There is no integrated firstboot check anymore.
    * All Images uses [runit](http://smarden.org/runit/) instead of supervisord. runit is a lightweight init system with service supervision. runit is configured to load and monitor all services in the `/etc/service` directory.
* Healhcheck
    * [goss](https://github.com/aelsabbahy/goss) is now integrated per default. goss is a tool for validating a server’s configuration and health. goss is preconfigured to run several checks which are automatically exposed to Docker health check. If you are using [Kubernetes](https://kubernetes.io/), you can run `goss validate` as liveness/readyness probe. If you want to add you own checks, you can place it in the `/etc/goss/conf.d` directory.
* They are many images we we don't support in future and which are only receiving security updates. You will find a list below:
    * whatwedo/apache-php56
    * whatwedo/apache-php70
    * whatwedo/apache-php71
    * whatwedo/apache-php72
    * whatwedo/apache
    * whatwedo/bind
    * whatwedo/cloudflare-railgun
    * whatwedo/docker
    * whatwedo/elasticsearch
    * whatwedo/golang
    * whatwedo/icinga2
    * whatwedo/java
    * whatwedo/kibana
    * whatwedo/logstash-forwarder
    * whatwedo/logstash
    * whatwedo/mariadb
    * whatwedo/memcached
    * whatwedo/mongodb
    * whatwedo/nextcloud
    * whatwedo/node
    * whatwedo/owncloud
    * whatwedo/postgres
    * whatwedo/puppet-client
    * whatwedo/redis
    * whatwedo/ruby
    * whatwedo/squid
    * whatwedo/tomcat
    * whatwedo/wordpress
* PHP/Symfony
    * Images are based on PHP 7.3 now
    * `composer` is now installed per default
    * There are no different image repos with different PHP versions. Instead the PHP version is fixed based on the Docker image tag.
* Symfony
    * Symfony images do not longer container Node/NPM. We suggest do use a Docker multi stage build together with our new `whatwedo/yarn` image instead.
    
You will find the full list of all new images and their documentation under: https://github.com/whatwedo/docker-base-images/tree/v2.0

**Comment by lukasluecke** [comment]
@xarem Maybe we should move this to a `CHANGELOG.md` or similar? Not sure I like this as an open issue forever 🙈
