### ISSUE TITLE
Move opcache settings to conf.d

### ISSUE THREAD

**Issue by xarem** [whatwedo/docker-base-images#33]
f.ex. use `/etc/php7/conf.d/50_symfony2.ini` instead of a RUN

https://github.com/whatwedo/docker-base-images/blob/fde2c7dd4d0ec5c9e166782af5d30e8e04b72faa/images/symfony2/Dockerfile#L5

**Comment by s4mpl3d** [comment]
@xarem done :+1: 
373d3c57c5d825801d8373b1782db867dc76903a
