### ISSUE TITLE
Question about ServerAdmin in httpd?

### ISSUE THREAD

**Issue by hh-project-config** [whatwedo/docker-base-images#34]
Thanks for providing the container! 

I am doing a research aiming at finding issues in configuration files. After pulling the image we notice that `ServerAdmin` is set to `webmaster@localhost` in `/etc/apache2/sites-enabled/000-default.conf`.  

However, the HttpD [official document](https://httpd.apache.org/docs/2.4/mod/core.html#servername) recommends the following config:
*  `ServerAdmin`: "However, it's recommended to actually use an email address, since there are a lot of CGI scripts that make that assumption. "

Could you please provide a knob to specify the value of `ServerAdmin`?

**Comment by xarem** [comment]
Hey @hh-project-config 

Thanks for reaching us out.

Are you using the Version 1.x of our containers? We're not supporting them anymore and we recommend to switch to our v2 containers. Those are using nginx instead and nginx does not expose any information about the server administrator.

If you want to stick with apache from v1.7, we recommend that you extend our image and replace it with sed (if you don't want to overwrite all the files):

```
FROM whatwedo/apache:v1.7 as base
RUN sed -i s/ServerAdmin.*/ServerAdmin\ system@whatwedo.ch/g /etc/apache2/sites-available/*
```

But keep in mind that the containers in v1.7 are based on Ubuntu 14.04 LTS and are EOL. We recommend using the official httpd images (https://hub.docker.com/_/httpd).

Kind regards
Ueli
