### ISSUE TITLE
Links to images in README broken (inconsistent branch name for v2.1)

### ISSUE THREAD

**Issue by lukasluecke** [whatwedo/docker-base-images#37]
The links point to `v2.1` branch, but the branch is still called `v2.1-dev`.

**Comment by xarem** [comment]
@lukasluecke It is on purpose because I want to remove `-dev` from the branch as soon as possible (around end of january) and didn't want to forget to remove it in the readme 😄

**Comment by lukasluecke** [comment]
It's just a bad first impression, since the `v2.1-dev` is set as our default branch already 🙈

**Comment by xarem** [comment]
v2.1-dev has been removed and replaced with v2.1. I'll improve this workflow in the next release
