### ISSUE TITLE
Symfony 5 Container v2.1 nicht sauber getaggt

### ISSUE THREAD

**Issue by xarem** [whatwedo/docker-base-images#40]
https://github.com/whatwedo/docker-base-images/tree/v2.1/images/symfony5

existiert aber falsch benannt etc.

**Comment by xarem** [comment]
`whatwedo/symfony5:v2.1` and `whatwedo/symfony5:v2.2` is available now

ping @PReimers

**Comment by PReimers** [comment]
> `whatwedo/symfony5:v2.1` and `whatwedo/symfony5:v2.2` is available now

Thank you @xarem 

Time to change all docker files 🙈
