### ISSUE TITLE
Use docker:20.10-dind instead of docker:dind for CI

### ISSUE THREAD

**Issue by s4mpl3d** [whatwedo/docker-base-images#56]
For our current CI we should use the image `docker:20.10-dind`, not `docker:dind`.

`docker:dind` currently throws a permission error on build; this isn't the case with `docker:20.10-dind 

```
#8 11.48 make: /bin/sh: Operation not permitted
```

**Comment by Ruesa18** [comment]
Instead of 20.10 I used 19.03 because there seems to be a problem with the new images/our runner configuration. So I used one of the workarounds mentioned [here](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4501).

**Comment by Ruesa18** [comment]
Latest Pipeline: https://dev.whatwedo.ch/whatwedo/docker-base-images/-/pipelines/110103
;)

**Comment by Ruesa18** [comment]
Status-Update: @s4mpl3d has set the configuration for TLS inside the .gitlab-ci.yml, as described in the mentioned "workarounds" above.
This means we can now use version 20.10 of dind. This will be rolled out with V2.5 of the docker-base-images repository.
See #59 for more infos
