### ISSUE TITLE
icinga sending notifications via email

### ISSUE THREAD

**Issue by chesty** [whatwedo/docker-base-images#6]
How do people enable email notifications?
icinga is running a script (/etc/icinga2/scripts/mail-service-notification.sh) which tries to execute the mail command, and there's no mail command installed.
It's an easy fix to install the mail command, but I'm wondering why it's missing, I thought maybe there is a reason. surely I'm not the first person to want to enable email notifications? what does everyone else do?

**Comment by n3r0-ch** [comment]
Sending mails is currently not supported. We send our notifications to Slack.

Just installing the `mail` command will not work without installing a MTA. One possible workaround is to write a own script which sends mails via SMTP.

**Comment by chesty** [comment]
ok thanks, the only thing I know about slack is it exists, I'll look into mattermost though, I think it will be useful in other areas too.
