### ISSUE TITLE
Add `npm` images

### ISSUE THREAD

**Issue by renestalder** [whatwedo/docker-base-images#61]
Add `npm` images as a future replacement for the outdated `yarn` version images.

It basically requires `RUN apk add --update npm` on the base images.

## Bonus: Make the npm version controllable.

The nodejs version dictates  what version of npm is used. There are cases we might want to try out a newer version.

## Other notes that might be useful

A preferred way to install npm packages might be:

```
npm install --prefer-offline --no-audit --cache ./.npm
```

Or a clean install that deletes `node_modules` before running:

```
npm ci --prefer-offline --no-audit --cache ./.npm
```

1. You want to use `--prefer-offline` when running in a cached environment to make use of that cache
2. You might want to use `npm ci` when you want to make you have a clean install of all dependencies. You will not benefit from a cache `node_modules` folder.
3. You might want to strictly define the location of the cache folder and cache that folder, in case you would rather not cache all `node_modules`.

**Comment by renestalder** [comment]
Sounds about right. In any way, every project still has the option to overwrite it in the Dockerfile by pulling the potential npm image and then doing something like `npm install -g npm@<version>` (the official way to handling npm versions).

My initial thought was that this could be a built-in feature, but on the other side, as it is so easy to change the version, it probably doesn't matter and doesn't require that bonus.

**Comment by xarem** [comment]
introduced in [v2.8](https://github.com/whatwedo/docker-base-images/tree/v2.8) (`whatwedo/nodejs`)
