### ISSUE TITLE
ppa:ondrej/php5-5.6 does not exists

### ISSUE THREAD

**Issue by crivetechie** [whatwedo/docker-base-images#7]
I have forked your great repo to add jmx4perl package to icinga2 but building icinga2 image gives an error on `add-apt-repository -y ppa:ondrej/php5-5.6`:
`Cannot add PPA: 'ppa:ondrej/php5-5.6'.
Please check that the PPA name or format is correct.`

It looks like ppa:ondrej/php5-5.6 has been deprecated in favour of ppa:ondrej/php, I am not sure though if it provides the same functionalities your image needs

**Comment by n3r0-ch** [comment]
PPA issue is fixed. New image builds should be available until tomorrow morning.
