### ISSUE TITLE
date.timezone not set

### ISSUE THREAD

**Issue by crivetechie** [whatwedo/docker-base-images#8]
with the [fix to php repo](https://github.com/whatwedo/docker-base-images/commit/fc3a61200ea31d3fa9481ad04cf01271c5456b26) installing php5.6 the default timezone of php is no longer set as the location of php.ini file has changed from /etc/php5/apache2/php.ini to /etc/php/5.6/apache2/php.ini

**Comment by n3r0-ch** [comment]
Timezone issue is fixed. New image builds should be available in about 6 hours.
