### ISSUE TITLE
Add custom script to be execute on boot phase

### ISSUE THREAD

**Issue by pgom** [whatwedo/docker-base-images#9]
I'm building a Docker image based on `nginx-php70`. I want to add a new script to be executed when the container is booted but I'm having a hard time figuring out how to properly do it. 

P.S. I'm a beginner in a Docker and this might be more related to that than to this image in particular.

**Comment by xarem** [comment]
Hi @pgom 

The easiest way to add a script to execute on boot time is to add it to `/bin/everyboot` or `/bin/firstboot`

For example:

```
FROM whatwedo/nginx-php70:latest

# Add files
ADD . /var/www

# show information about PHP
RUN echo "php -i" >> /bin/everyboot
```

**Attention:** `/bin/everyboot` is blocking: nginx and php-fpm will be started after this script is executed successfully. You find a lot of examples in our [GitLab](https://github.com/whatwedo/docker-base-images/blob/master/dist/gitlab/Dockerfile) image, which has a long initialisation script

I would advise against dong anything after nginx is booted. You can run a service with supervisord which waits until a successful HTTP connection can be executed but that's only reasonable for a everrunning process. An other option is to start nginx in the boot script, then stop it again. We did something similar in the [MariaDB](https://github.com/whatwedo/docker-base-images/blob/master/dist/mariadb/Dockerfile) image to create the new database the first time the container starts.

**Comment by pgom** [comment]
Thanks for your reply @xarem. 

I just want to add script to generate environment variables based file to be consumed by my application. 

I'll give that a try 👍

**Comment by pgom** [comment]
This is was exactly what I've looking for. Thanks a lot for your support, @xarem
